name: Basic Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test imports
      run: python tests/test_imports.py
    
    - name: Train model for testing
      run: python tests/test_model_training.py
    
    - name: Test model accuracy with known cases
      run: python tests/test_model_accuracy.py
    
    - name: Test model consistency and non-randomness  
      run: python tests/test_model_consistency.py
    
    - name: Test edge cases and input validation
      run: python tests/test_model_validation.py
    
    - name: Performance summary
      run: |
        echo "🎉 All model accuracy and consistency tests passed!"
        echo "✅ Model shows reasonable discrimination between risk levels"
        echo "✅ Model predictions are consistent and non-random"
        echo "✅ Model handles edge cases appropriately"
        echo "✅ Input validation works correctly" 